
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace EdiuxTemplateWebApp.Models.AspNetModels
{

using System;
    using System.Collections.Generic;
    
public partial class aspnet_WebEvent_Events
{

    public string EventId { get; set; }

    public System.DateTime EventTimeUtc { get; set; }

    public System.DateTime EventTime { get; set; }

    public string EventType { get; set; }

    public decimal EventSequence { get; set; }

    public decimal EventOccurrence { get; set; }

    public int EventCode { get; set; }

    public int EventDetailCode { get; set; }

    public string Message { get; set; }

    public string ApplicationPath { get; set; }

    public string ApplicationVirtualPath { get; set; }

    public string MachineName { get; set; }

    public string RequestUrl { get; set; }

    public string ExceptionType { get; set; }

    public string Details { get; set; }

}

}
