//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiuxTemplateWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Notifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Notifications()
        {
            this.OriginalNotifications = new HashSet<System_Notifications>();
        }
    
        public int Id { get; set; }
        public int FromUserId { get; set; }
        public int TargetUserId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string MessageLink { get; set; }
        public bool Read { get; set; }
        public Nullable<int> RelayNotificationId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> RelayTime { get; set; }
    
        public virtual ApplicationUser Sender { get; set; }
        public virtual ApplicationUser Recipient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Notifications> OriginalNotifications { get; set; }
    }
}
