//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdiuxTemplateWebApp.Models.AspNetModels
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class aspnet_Applications
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public aspnet_Applications()
		{
			this.aspnet_Membership = new HashSet<aspnet_Membership>();
			this.aspnet_Paths = new HashSet<aspnet_Paths>();
			this.aspnet_Roles = new HashSet<aspnet_Roles>();
			this.aspnet_Users = new HashSet<aspnet_Users>();
			this.aspnet_VoidUsers = new HashSet<aspnet_VoidUsers>();
			this.Menus = new HashSet<Menus>();
		}

		public string ApplicationName { get; set; }
		public string LoweredApplicationName { get; set; }
		[Key]
		public System.Guid ApplicationId { get; set; }
		public string Description { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<aspnet_Membership> aspnet_Membership { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<aspnet_Paths> aspnet_Paths { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<aspnet_VoidUsers> aspnet_VoidUsers { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Menus> Menus { get; set; }
	}
}
